import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {randomUUID} from 'node:crypto';
import {PortalService} from '../portal-service.mjs';
import {MACHINES} from '../dist/model.js';
test('authenticated Portal submit/reconcile reaches REAL native queue metadata, with no resubmit or spec edits',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'gpuq-native-display-http-')),status=join(dir,'status'),bootstrap=join(dir,'bootstrap'),password='Native-Display-Test-2026!';
  await writeFile(bootstrap,JSON.stringify({username:'admin',password}));
  await writeFile(status,JSON.stringify({version:1,checkedAt:new Date().toISOString(),hosts:MACHINES.map(m=>({id:m.id,reachable:true,gpus:Array.from({length:m.cards},(_,index)=>({index,uuid:'GPU-'+index,memoryTotalMiB:32768,processesAvailable:true,processes:[]})),gpuq:{connected:true,observeOnly:false,capabilities:['console-task-display-v1']}}))}));
  const child=spawn('python3',[new URL('./fixtures/native-display-rpc.py',import.meta.url).pathname],{stdio:['pipe','pipe','pipe']});
  let stderr='';child.stderr.on('data',c=>stderr+=c);const pending=new Map();let sequence=0;
  const ready=new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>{if(code)reject(Error(stderr));});const lines=createInterface({input:child.stdout});lines.on('line',line=>{const message=JSON.parse(line);if(message.ready)return resolve();const waiter=pending.get(message.id);pending.delete(message.id);message.ok?waiter.resolve(message.result):waiter.reject(Error(message.error));});});
  await ready;const call=(operation,args={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,operation,args})+'\n');});
  const envelopes=[];const service=await PortalService.open(join(dir,'db'),bootstrap,status,async(machine,op,args)=>{envelopes.push({op,args:structuredClone(args)});return call(op,args);});clearInterval(service.executionTimer);
  t.after(async()=>{service.close();child.stdin.end();await new Promise(r=>child.once('close',r));await rm(dir,{recursive:true,force:true});});
  const admin=await service.login('admin',password),user=(await service.invoke(admin.token,'users.create',{username:'刘鹏亮',name:'真正姓名',password})).result;
  await service.invoke(admin.token,'policy.save',{userId:user.id,policyVersion:0,total:1,limits:{'gpu-1':1}});
  const member=await service.login('刘鹏亮',password),args={key:randomUUID(),machine:'gpu-1',cards:1,name:'fashion-hm-teachers0-20261003',description:'当前轮次内容',argv:['python','train.py']};
  const submitted=(await service.invoke(member.token,'jobs.submit',args)).result;
  while(service.reconciling)await new Promise(r=>setTimeout(r,5));
  await service.reconcile();const inspect=await call('inspect');assert.equal(inspect.jobs.length,1);assert.equal(inspect.submitCalls,1);
  assert.equal(inspect.jobs[0].submit_key,submitted.id);assert.match(inspect.jobs[0].owner,/^portal-/);
  assert.ok(inspect.table.includes('真正姓名 (刘鹏亮)'));assert.ok(inspect.table.includes(args.name));
  assert.equal(inspect.jobs[0].display_metadata.description,args.description);
  const spec=structuredClone(service.store.jobs[0].spec);await call('erase-display');await service.reconcile();
  const repaired=await call('inspect');assert.ok(repaired.table.includes(args.name));assert.equal(repaired.submitCalls,1);assert.deepEqual(service.store.jobs[0].spec,spec);
  assert.ok(envelopes.filter(e=>e.op==='sync').every(e=>e.args.metadata.submitter.username==='刘鹏亮'));assert.equal(spec.description,undefined);assert.equal(spec.submitterName,undefined);
});
